export enum UserRole {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  LIAISON_OFFICER = 'LIAISON_OFFICER',
  SPECIALIST='SPECIALIST',
  GATEKEEPER = 'GATEKEEPER',
  HOSPITAL_APPROVER='HOSPITAL_APPROVER' // optional, handles patient entry verification
}
